Repository AY2425S1-CS2103T-F14A-3/tp, pull requests merged in 2024-11, with the labels that each got.

#150 Update UG with command details and landing page with CI/codecov badges
  README.md
  docs/UserGuide.md
  docs/index.md
Labels: type.Task, priority.Medium

#162 Fix typos and grammatical errors in User Guide
  docs/UserGuide.md
Labels: type.Task, priority.Medium, severity.VeryLow

#164 Decouple blacklist command from find command
  src/main/java/seedu/address/logic/commands/BlacklistListCommand.java
  src/main/java/seedu/address/logic/commands/WhitelistListCommand.java
  src/main/java/seedu/address/model/person/ArgumentPredicate.java
  src/main/java/seedu/address/model/person/ArgumentPredicateToFail.java
Labels: type.Enhancement, priority.Medium

#169 Improve flexibility of deadline field
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Deadline.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/parser/ParserUtilDateTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/DeadlineTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: type.Enhancement, priority.Medium

#171 Update UserGuide
  docs/UserGuide.md
Labels: priority.Medium

#176 Update UG with section on acceptable values by field
  docs/UserGuide.md
Labels: type.Enhancement, priority.Medium

#178 Attempt to fix incorrect table rendering issue
  docs/UserGuide.md
Labels: priority.High, type.Bug, severity.High

#179 Update table CSS to make it wider than rest of the content
  docs/UserGuide.md
  docs/_sass/minima/_base.scss
Labels: type.Enhancement, priority.Medium

#192 Fix grammatical errors in command help messages
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/UnarchiveCommand.java
Labels: type.Bug, priority.Medium, severity.VeryLow

#241 Adjustments to UG styling
  docs/UserGuide.md
  docs/_sass/minima/_base.scss
Labels: priority.High

#248 Fix invalid phone number error message
  src/main/java/seedu/address/model/person/ClientStatus.java
  src/main/java/seedu/address/model/person/Phone.java
Labels: priority.High, type.Bug, severity.High

#246 Fix error message for invalid client status
  src/main/java/seedu/address/model/person/ClientStatus.java
Labels: type.Enhancement, priority.Medium, severity.Low

#250 Specify how tag-finding works
  docs/UserGuide.md
Labels: type.Bug, priority.Medium, severity.Medium

#251 Update UG to specify that only 2 commands can be used when viewing archived list
  docs/UserGuide.md
Labels: type.Bug, priority.Medium, severity.Medium

#255 Add exit command to command summary and fix add command params order
  docs/UserGuide.md
Labels: type.Bug, priority.Medium, severity.Low

#256 Fix formatting issue in UG
  docs/UserGuide.md
Labels: type.Bug, priority.Medium, severity.Low, severity.Medium

#260 Update UG with new phone number input restrictions
  docs/UserGuide.md
Labels: type.Bug, priority.Medium, severity.Medium

#267 Fix datetime restriction noted in UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Bug, priority.Medium, severity.Low
