Repository AY2425S1-CS2103T-F14A-3/tp, pull requests merged in 2024-10, with the labels that each got.

#6 Add jktang14.png
  docs/images/jktang14.png
Labels: type.Task

#19 Branch add self image
  .gitignore
  docs/images/dinoman44.png
Labels: type.Task

#24 Add AboutUs
  docs/AboutUs.md
Labels: type.Task

#22 Update AboutUs to include myself
  docs/AboutUs.md
  docs/team/dinoman44.md
Labels: priority.High, type.Task

#23 Update aboutus page
  docs/AboutUs.md
Labels: type.Task

#26 Update project website navbar text
  docs/_config.yml
  docs/_sass/minima/_base.scss
Labels: priority.High, type.Task

#27 Complete Week 6 Task 3C - Add NFRs to DG
  docs/DeveloperGuide.md
Labels: priority.High, type.Task

#38 Fix NFR 6 phrasing
  docs/DeveloperGuide.md
Labels: type.Task

#40 Add Project Status to Add Command
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/ProjectStatus.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/ProjectStatusTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Epic, type.Story, severity.Low

#43 Add ClientStatus field
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/ClientStatus.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/ClientStatusTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High, type.Epic, type.Story

#44 Add payment status field
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/PaymentStatus.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High, type.Epic, type.Story

#52 Person.java: update isSamePerson method to check for email and phone
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: priority.High, type.Task

#51 Edit formatting of name and address parameter
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Phone.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
Labels: priority.High, type.Task

#59 Add support for deletion by name or id
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: priority.High

#62 Update product version to v1.3
  src/main/java/seedu/address/MainApp.java
Labels: priority.High

#71 Mark overdue projects with the [OVERDUE] flag
  src/main/java/seedu/address/model/person/Deadline.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/PersonCard.java
Labels: type.Enhancement, priority.Medium

#75 Add sort command
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
Labels: priority.High, type.Task

#80 Update GUI
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
Labels: type.Task, priority.Medium

#83 Add blacklist and whitelist commands
  .gitignore
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/BlacklistCommand.java
  src/main/java/seedu/address/logic/commands/WhitelistCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/BlacklistCommandParser.java
  src/main/java/seedu/address/logic/parser/WhitelistCommandParser.java
  src/main/java/seedu/address/model/person/ClientStatus.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: priority.High, type.Epic, type.Story

#87 Update UML diagrams and User Guide with new Blacklist and Whitelist commands
  .gitignore
  docs/UserGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  src/main/java/seedu/address/logic/parser/WhitelistCommandParser.java
Labels: priority.High, type.Task

#95 view/DarkTheme.css: Fix syntax error
  src/main/resources/view/DarkTheme.css
Labels: type.Bug, priority.Medium

#96 docs/DeveloperGuide.md: Fix error with image filepath
  docs/DeveloperGuide.md
Labels: priority.High, type.Bug

#103 add upcoming project deadlines in footer
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/ReminderManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/resources/images/reminder.png
  src/main/resources/view/StatusBarFooter.fxml
  src/test/java/seedu/address/model/person/ReminderManagerTest.java
Labels: type.Task

#113 fix duplicate project status allowed in Add Command
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
Labels: severity.Medium, alpha-bug

#116 UI: Adjust Payment Status tooltip text
  src/main/java/seedu/address/ui/PersonCard.java
Labels: type.Task

#121 Fix reminder
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/ReminderManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/person/ReminderManagerTest.java
Labels: priority.High, type.Bug, severity.Medium, alpha-bug

#130 Update User guide with reminder
  docs/UserGuide.md
  docs/images/reminder.png
  docs/img.png
Labels: priority.High, type.Task

#136 fix reminder
  docs/UserGuide.md
Labels: priority.Low

#137 Update User Guide to better reflect name field restictions
  build.gradle
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/BlacklistCommand.java
  src/main/java/seedu/address/logic/commands/WhitelistCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/WhitelistCommandParser.java
Labels: severity.Medium, alpha-bug

#139 Disallow > 1 client status prefix in params for whitelist command
  src/main/java/seedu/address/logic/parser/WhitelistCommandParser.java
  src/main/java/seedu/address/model/person/ClientStatus.java
Labels: priority.High, severity.Medium, alpha-bug

#140 Fix typo in add command usage message
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: type.Bug, severity.Low, alpha-bug
